export default [
  { id: 'stella', url: require('@/assets/stella.png'), button: 'like', prijs: '1,40' },
  { id: 'cola', url: require('@/assets/coca-cola.jpg'), button: 'like', prijs: '1' },
  { id: 'gerolsteiner-sprudel', url: require('@/assets/gerolsteiner-sprudel.png'), button: 'like', prijs: '0,80' },
  { id: 'cornet', url: require('@/assets/cornet.jpg'), button: 'like', prijs: '2,30' },
  { id: 'duvel', url: require('@/assets/duvel.png'), button: 'like', prijs: '2,30' },
  { id: 'omer', url: require('@/assets/omer.png'), button: 'like', prijs: '2,30' },
  { id: 'rouge', url: require('@/assets/rouge.png'), button: 'like', prijs: '2,50' },
  { id: 'kriek', url: require('@/assets/kriek.png'), button: 'like', prijs: '2' },
  { id: 'desperados', url: require('@/assets/desperados.png'), button: 'like', prijs: '2,50' },
  { id: 'appel', url: require('@/assets/appel.png'), button: 'like', prijs: '2,50' },
  { id: 'red', url: require('@/assets/red.png'), button: 'like', prijs: '2,50' },
  { id: 'rose', url: require('@/assets/rose.jpg'), button: 'like', prijs: '2,50' },
  { id: 'wit', url: require('@/assets/wit.png'), button: 'like', prijs: '2' },
  { id: 'stellazero', url: require('@/assets/stellazero.png'), button: 'like', prijs: '1,60' },
  { id: 'colazero', url: require('@/assets/colazero.jpg'), button: 'like', prijs: '1' },
  { id: 'gerolsteiner-plat', url: require('@/assets/gerolsteiner-plat.png'), button: 'like', prijs: '0,80' },
  { id: 'lemon', url: require('@/assets/lemon.png'), button: 'like', prijs: '1' },
  { id: 'orange', url: require('@/assets/orange.png'), button: 'like', prijs: '1' },
  { id: 'icet', url: require('@/assets/icet.jpg'), button: 'like', prijs: '1' },
  { id: 'icegreen', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },
];

