export default [
  { id: 'rouge0', url: require('@/assets/rouge.png'), button: 'like', prijs: '2,50' },
  { id: 'wit0', url: require('@/assets/wit.png'), button: 'nope', prijs: '2' },
  { id: 'lemon0', url: require('@/assets/lemon.png'), button: 'like', prijs: '1' },
  { id: 'kriek0', url: require('@/assets/kriek.png'), button: 'nope', prijs: '2' },
  { id: 'stellazero0', url: require('@/assets/stellazero.png'), button: 'super', prijs: '1,60' },
  { id: 'cornet', url: require('@/assets/cornet.jpg'), button: 'like', prijs: '2,30' },

  { id: 'colazero1', url: require('@/assets/colazero.jpg'), button: 'like', prijs: '1' },
  { id: 'cola1', url: require('@/assets/coca-cola.jpg'), button: 'like', prijs: '1' },
  { id: 'orange1', url: require('@/assets/orange.png'), button: 'like', prijs: '1' },
  { id: 'stella1', url: require('@/assets/stella.png'), button: 'like', prijs: '1,40' },
  { id: 'icegreen1', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },
  { id: 'icet', url: require('@/assets/icet.jpg'), button: 'like', prijs: '1' },

  { id: 'red2', url: require('@/assets/red.png'), button: 'like', prijs: '2,50' },
  { id: 'wit2', url: require('@/assets/wit.png'), button: 'like', prijs: '2' },
  { id: 'kriek2', url: require('@/assets/kriek.png'), button: 'like', prijs: '2' },
  { id: 'stellazero2', url: require('@/assets/stellazero.png'), button: 'like', prijs: '1,60' },
  { id: 'icegreen2', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },
  { id: 'duvel2', url: require('@/assets/duvel.png'), button: 'like', prijs: '2,30' },
  { id: 'omer', url: require('@/assets/omer.png'), button: 'like', prijs: '2,30' },

  { id: 'rouge3', url: require('@/assets/rouge.png'), button: 'like', prijs: '2,50' },
  { id: 'wit3', url: require('@/assets/wit.png'), button: 'nope', prijs: '2' },
  { id: 'lemon3', url: require('@/assets/lemon.png'), button: 'like', prijs: '1' },
  { id: 'kriek3', url: require('@/assets/kriek.png'), button: 'nope', prijs: '2' },
  { id: 'stellazero3', url: require('@/assets/stellazero.png'), button: 'super', prijs: '1,60' },
  { id: 'red', url: require('@/assets/red.png'), button: 'like', prijs: '2,50' },

  { id: 'red4', url: require('@/assets/red.png'), button: 'like', prijs: '2,50' },
  { id: 'wit4', url: require('@/assets/wit.png'), button: 'like', prijs: '2' },
  { id: 'kriek4', url: require('@/assets/kriek.png'), button: 'like', prijs: '2' },
  { id: 'stellazero4', url: require('@/assets/stellazero.png'), button: 'like', prijs: '1,60' },
  { id: 'icegreen4', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },
  { id: 'duvel4', url: require('@/assets/duvel.png'), button: 'like', prijs: '2,30' },
  { id: 'rouge', url: require('@/assets/rouge.png'), button: 'like', prijs: '2,50' },

  { id: 'orange5', url: require('@/assets/orange.png'), button: 'like', prijs: '1' },
  { id: 'stella5', url: require('@/assets/stella.png'), button: 'like', prijs: '1,40' },
  { id: 'cola', url: require('@/assets/coca-cola.jpg'), button: 'like', prijs: '1' },

  { id: 'colazero6', url: require('@/assets/colazero.jpg'), button: 'like', prijs: '1' },
  { id: 'cola6', url: require('@/assets/coca-cola.jpg'), button: 'like', prijs: '1' },
  { id: 'orange6', url: require('@/assets/orange.png'), button: 'like', prijs: '1' },
  { id: 'stella6', url: require('@/assets/stella.png'), button: 'like', prijs: '1,40' },
  { id: 'icegreen6', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },
  { id: 'desperados', url: require('@/assets/desperados.png'), button: 'like', prijs: '2,50' },
  
  { id: 'lemon7', url: require('@/assets/lemon.png'), button: 'like', prijs: '1' },
  { id: 'kriek7', url: require('@/assets/kriek.png'), button: 'nope', prijs: '2' },
  { id: 'stellazero7', url: require('@/assets/stellazero.png'), button: 'super', prijs: '1,60' },
  { id: 'appel', url: require('@/assets/appel.png'), button: 'like', prijs: '2,50' },
  
  { id: 'kriek8', url: require('@/assets/kriek.png'), button: 'like', prijs: '2' },
  { id: 'stellazero8', url: require('@/assets/stellazero.png'), button: 'like', prijs: '1,60' },
  { id: 'icegreen8', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },
  { id: 'duvel8', url: require('@/assets/duvel.png'), button: 'like', prijs: '2,30' },
  { id: 'gerolsteiner-plat', url: require('@/assets/gerolsteiner-plat.png'), button: 'like', prijs: '0,80' },
  
  { id: 'stellazero9', url: require('@/assets/stellazero.png'), button: 'like', prijs: '1,60' },
  { id: 'icegreen9', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },
  { id: 'duvel9', url: require('@/assets/duvel.png'), button: 'like', prijs: '2,30' },
  { id: 'wit', url: require('@/assets/wit.png'), button: 'like', prijs: '2' },
  
  { id: 'rouge10', url: require('@/assets/rouge.png'), button: 'like', prijs: '2,50' },
  { id: 'wit10', url: require('@/assets/wit.png'), button: 'nope', prijs: '2' },
  { id: 'lemon10', url: require('@/assets/lemon.png'), button: 'like', prijs: '1' },
  { id: 'kriek10', url: require('@/assets/kriek.png'), button: 'nope', prijs: '2' },
  { id: 'stellazero10', url: require('@/assets/stellazero.png'), button: 'super', prijs: '1,60' },
  { id: 'orange', url: require('@/assets/orange.png'), button: 'like', prijs: '1' },
  
  { id: 'kriek11', url: require('@/assets/kriek.png'), button: 'like', prijs: '2' },
  { id: 'stella11', url: require('@/assets/stella.png'), button: 'like', prijs: '1,40' },
  { id: 'lemon11', url: require('@/assets/lemon.png'), button: 'like', prijs: '1' },
  { id: 'icegreen', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },

  { id: 'gerolsteiner-sprudel12', url: require('@/assets/gerolsteiner-sprudel.png'), button: 'like', prijs: '0,80' },
  { id: 'kriek12', url: require('@/assets/kriek.png'), button: 'like', prijs: '2' },
  { id: 'duvel', url: require('@/assets/duvel.png'), button: 'like', prijs: '2,30' },
  
  { id: 'kriek13', url: require('@/assets/kriek.png'), button: 'like', prijs: '2' },
  { id: 'stellazero13', url: require('@/assets/stellazero.png'), button: 'like', prijs: '1,60' },
  { id: 'icegreen13', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },
  { id: 'duvel13', url: require('@/assets/duvel.png'), button: 'like', prijs: '2,30' },
  { id: 'rose', url: require('@/assets/rose.jpg'), button: 'like', prijs: '2,50' },
  
  { id: 'icegreen14', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },
  { id: 'rose14', url: require('@/assets/rose.jpg'), button: 'like', prijs: '2,50' },
  { id: 'wit14', url: require('@/assets/wit.png'), button: 'like', prijs: '2' },
  { id: 'colazero', url: require('@/assets/colazero.jpg'), button: 'like', prijs: '1' },
  
  { id: 'colazero15', url: require('@/assets/colazero.jpg'), button: 'like', prijs: '1' },
  { id: 'cola15', url: require('@/assets/coca-cola.jpg'), button: 'like', prijs: '1' },
  { id: 'orange15', url: require('@/assets/orange.png'), button: 'like', prijs: '1' },
  { id: 'stella15', url: require('@/assets/stella.png'), button: 'like', prijs: '1,40' },
  { id: 'icegreen15', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },
  { id: 'gerolsteiner-sprudel', url: require('@/assets/gerolsteiner-sprudel.png'), button: 'like', prijs: '0,80' },
  
  { id: 'colazero16', url: require('@/assets/colazero.jpg'), button: 'like', prijs: '1' },
  { id: 'cola16', url: require('@/assets/coca-cola.jpg'), button: 'like', prijs: '1' },
  { id: 'stella16', url: require('@/assets/stella.png'), button: 'like', prijs: '1,40' },
  { id: 'icegreen16', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },
  { id: 'orange16', url: require('@/assets/orange.png'), button: 'like', prijs: '1' },
  { id: 'kriek', url: require('@/assets/kriek.png'), button: 'like', prijs: '2' },
  
  { id: 'kriek17', url: require('@/assets/kriek.png'), button: 'like', prijs: '2' },
  { id: 'stella17', url: require('@/assets/stella.png'), button: 'like', prijs: '1,40' },
  { id: 'lemon17', url: require('@/assets/lemon.png'), button: 'like', prijs: '1' },
  { id: 'stella', url: require('@/assets/stella.png'), button: 'like', prijs: '1,40' },

  { id: 'colazero18', url: require('@/assets/colazero.jpg'), button: 'like', prijs: '1' },
  { id: 'cola18', url: require('@/assets/coca-cola.jpg'), button: 'like', prijs: '1' },
  { id: 'orange18', url: require('@/assets/orange.png'), button: 'like', prijs: '1' },
  { id: 'lemon', url: require('@/assets/lemon.png'), button: 'like', prijs: '1' },

  { id: 'kriek19', url: require('@/assets/kriek.png'), button: 'like', prijs: '2' },
  { id: 'stellazero19', url: require('@/assets/stellazero.png'), button: 'like', prijs: '1,60' },
  { id: 'icegreen19', url: require('@/assets/icegreen.jpg'), button: 'like', prijs: '1' },
  { id: 'stellazero', url: require('@/assets/stellazero.png'), button: 'like', prijs: '1,60' },

];

